import { type Metadata } from 'next'
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut
} from '@clerk/nextjs'
import {ConvexClerkProvider} from '../components/providers/ConvexClerkProvider'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/providers/ThemeProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
          </header>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>

          <SignedIn>
            <div className='min-h-screen'>
            <Navbar/>
            <main className='px-4 sm:px-6 lg:px-8'>{children}</main>
            </div>
          </SignedIn>

          <SignedOut>
            <RedirectToSignIn></RedirectToSignIn>
          </SignedOut>
          </ThemeProvider>
        </body>
      </html>
    </ConvexClerkProvider>
  )
}